services:
  rpi-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpi-dev
    hostname: rpi-dev
    ports:
      - "2225:22"
    networks:
      iotnet:
        ipv4_address: 192.168.2.10
    volumes:
      - ./ws:/workspace
      - ./pico:/pico
    tty: true

networks:
  iotnet:
    external: true
    name: iotnet